### PR TITLE
AUI-1891

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1891.  Can you review this change and if it is good, I will create a new AUI release for support.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mairatma** [comment]
Thanks, pr merged :)

**Comment by ZoltanTakacs** [comment]
Hey @jonmak08,

I was wondering if you have had a chance to deal with this backport. We really appreciate your help on this.

Thank you,
Zoltán

/cc @CsabaTurcsan

**Comment by jonmak08** [comment]
Hey @ZoltanTakacs and @CsabaTurcsan,

I am creating the release now for this issue.  Thanks for review this so quickly @mairatma!

Please let me know if you have any questions.  Thanks!

**Comment by ZoltanTakacs** [comment]
Hey @jonmak08,

Thank you for creating the release for it! We appreciate your help. :)

**Pull request merged**
