### PR TITLE
AUI-1908 Only block focusing on iframes outside of bounding box.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey @mairatma

I updated my fix.

Did I choose the correct branch for YUI3?

I need to fix this for Trunk and ee-6.2.x

Thanks
John.,

### CODE REVIEW

**Comment by mairatma** [comment]
Yes, I believe this is the right branch for 6.2, I'll go ahead and review :)

**Comment by mairatma** [comment]
Thanks a lot for the fix, I've merged it to [liferay's repo](https://github.com/liferay/yui3/commits/patched-v3.11.0).

Next time just remember to run the tests before sending the pr. There was a test for the iframe blocking logic that was failing with this change, and it detected a real bug which I fixed at https://github.com/liferay/yui3/commit/0d95ab6cde79ff75a0781df360637701f9438dfe before pushing. To run yui3 tests you just need to compile the changes first (running `shifter --walk` on the folder that changed) and then run `yogi test` on that folder.

**Comment by mairatma** [comment]
@jonmak08, could you help us with the next steps for updating Liferay 6.2 with this change?

**Comment by zxdgoal** [comment]
Thanks, Maira.

I am sorry for the bug. I was thinking the `bb` cannot be accessed directly in forEach.

I will run test when send a pr in next time.

**Comment by mairatma** [comment]
No problem :)

**Pull request merged**
