### PR TITLE
Aui 1549

### PR DESCRIPTION
**Pull request by travisrcory**

### CODE REVIEW

**Comment by mairatma** [comment]
@travisc5 I can't seem to be able to reproduce the problem this should be fixing on alloy's demo for the modal right now. I added a button to the bottom of the page after scrolling a lot, and the modal it opens is not scrolling back up to the top like https://issues.liferay.com/browse/LPP-12330 describes. Can you send me repro steps for the issue so I can understand the need for this change?

**Comment by travisrcory** [comment]
Use these repro steps.
1. build AlloyUI off of the 2.5.x branch. 
2. Navigate to the aui-modal demo
3. Edit the .html file to match the example in https://issues.liferay.com/browse/LPP-12330
4. make sure you have to scroll to see the show modal button.
5. Click button

**Comment by mairatma** [comment]
Thanks a lot for those repro steps, now I managed to repro this even on the current version of alloy, it's really weird behavior. I see now why your change fixed this, the problem here is actually that the focus is happening before WidgetPositionAlign positions the modal, so the browser gets scrolled up on focus since the modal hadn't been properly positioned yet.

I don't think that adding a setTimeout in that case is the best solution though. It will affect everything that uses WidgetModality, and will make focus become asynchronous, which can cause some unexpected problems in other people's code. Also, this is something that WidgetModality doesn't need all the time, it's only necessary when used in conjunction with WidgetPositionAlign, which is the case of alloy's modal module.

So I think it's best if we fix this on aui-modal itself. I tested it out and it seems like this can be fixed by just changing the order of alloy's modal augmentations, we just need to make sure that all WidgetPositionX modules are listed before WidgetModality there and it works fine. It'd be good to add a comment explaining this though, to prevent other people from changing the order back again. Feel free to open a pull request for me with this fix or something like that on alloy's side, or if you prefer I can make the change and send it to eduardo too, it's very small.

**Comment by travisrcory** [comment]
Hey Mairatma,

Wow, that makes a lot of sense. Thanks for looking into that. I do not have
a lot of bandwidth right now, do you think that you could make the change
and send it to Eduardo? Thank you for all of your help :) I really
appreciate it!

On Mon, Aug 11, 2014 at 12:01 PM, Maira Bello notifications@github.com
wrote:

> Thanks a lot for those repro steps, now I managed to repro this even on
> the current version of alloy, it's really weird behavior. I see now why
> your change fixed this, the problem here is actually that the focus is
> happening before WidgetPositionAlign positions the modal, so the browser
> gets scrolled up on focus since the modal hadn't been properly positioned
> yet.
> 
> I don't think that adding a setTimeout in that case is the best solution
> though. It will affect everything that uses WidgetModality, and will make
> focus become asynchronous, which can cause some unexpected problems in
> other people's code. Also, this is something that WidgetModality doesn't
> need all the time, it's only necessary when used in conjunction with
> WidgetPositionAlign, which is the case of alloy's modal module.
> 
> So I think it's best if we fix this on aui-modal itself. I tested it out
> and it seems like this can be fixed by just changing the order of alloy's
> modal augmentations, we just need to make sure that all WidgetPositionX
> modules are listed before WidgetModality there and it works fine. It'd be
> good to add a comment explaining this though, to prevent other people from
> changing the order back again. Feel free to open a pull request for me with
> this fix or something like that on alloy's side, or if you prefer I can
> make the change and send it to eduardo too, it's very small.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mairatma/yui3/pull/1#issuecomment-51824903.

## 

Best Regards,

## Travis Cory

_Liferay Symposium North America_
October 5-7, 2014 in Boston, MA
Early Bird ends August 15 | www.liferay.com/northamerica2014

**Comment by mairatma** [comment]
Sure, I'll send that to him then  :)

**Pull request closed without merging**
